### PR TITLE
Add strfmon

### PR DESCRIPTION
**Pull request by isage**
Requires https://github.com/vitasdk/buildscripts/pull/108

### CODE REVIEW

**Comment by d3m3vilurr** [comment]
Hello @isage, how about we just use copied/modified version of freebsd code?
https://github.com/vitasdk/newlib/blob/vita/winsup/cygwin/libc/strfmon.c

**Comment by isage** [comment]
It is simplified version from musl, which is rather shorter and easier (and we don't have locale support freebsd version requires)

**Comment by d3m3vilurr** [comment]
sorry for my late review. copying from musl is okay.
btw, can you add a license holder to head of copied code? (eg; https://github.com/vitasdk/newlib/blob/190169bc5/newlib/libc/string/strverscmp.c#L35-L56)
musl is MIT but newlib is mixed license.

**Comment by isage** [comment]
Sure, done

**Pull request merged**
